# Generated by Django 4.2.13 on 2026-05-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_auto_20260515_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
